#!/bin/bash


################################
#	optional parameter config file



dispatchOption(){
	
	printf "%s" "choose option (C)onsole or (G)rafical: "
	read -t 5 op


	if (( $? != 0)); then
		op=${defaultType^^}
	fi
echo "Debug op: ${op^^}"
		
	if [ "${op^^}" == "C" ]; then
	#	echo "console"
		exit 0

	elif [ "${op^^}" == "G" ]; then
	#	echo "grafical"
		startx		
		
	else
		exit 1
	fi


}

displayPresentation(){
	clear;

	echo "Welcome to `hostname` ${USER} date: `date`"
	echo -e "\n\n"
	echo "Lasts logins:"

	last  -n 3 $USER 
	echo -e "\n\n"

	dispatchOption




}


main(){
	
	################################
	#	if term exit
	#	first read the user defaul config file
	#	if no argument passed read defult config file
	#	if not exit 1

	if [ "$TERM" != "linux" ]; then
		exit 0;
	fi

	if [ -f ~/.config/displayManager/displayManager.conf ]; then
		
		. ~/.config/displayManager/displayManager.conf
		
	else
		if [ -f /etc/displayManager/displayManager.conf ]; then

			. /etc/displayManager/displayManager.conf
		else
			echo "No config file found"
			exit 1
		fi
	fi

	displayPresentation

}

################################
#	start the script


main 
